<?php

namespace Tests\Service\Status;

use App\Domain\Status\Entity\Course;
use App\Domain\Status\ValueObject\StudentInfo;
use App\Services\Status\StudentCreateService;
use Tests\TestCase;

class StudentCreateServiceTest extends TestCase
{
    protected $service;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = App(StudentCreateService::class);
    }

    public function test正常系()
    {
        $course = new Course(1, []);
        $studentInfo = new StudentInfo([
            "name" => "山田 太郎",
            "studentCode" => "b9999",
            "belongClass" => "9A"
        ]);

        $student = $this->service->create($studentInfo, $course);

        $this->assertTrue(true);
    }
}