<?php

namespace Tests\Application\Job;

use App\ApplicationService\JobApplicationService;
use App\Domain\GetCondition\GetCondition;
use App\Domain\Job\JobRepositoryInterface;
use Tests\TestCase;

/**
 * Created by PhpStorm.
 * User: user
 * Date: 2017/12/12
 * Time: 15:51
 */


class JobApplicationServiceTest extends TestCase
{
    /* @var JobRepositoryInterface $repo */
    protected $repo;
    /* @var JobApplicationService $jobApplicationService */
    private $jobApplicationService;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = app(JobRepositoryInterface::class);
        $this->jobApplicationService = new JobApplicationService($this->repo);
    }

    public function testSuccess()
    {
        $getCondition1 = new GetCondition('aaaa', 10);
        $getCondition2 = new GetCondition('bbbb', 15);

        $getConditions[] = $getCondition1;
        $getConditions[] = $getCondition2;

        $jobId = $this->jobApplicationService->registerJob('サーバーサイドマスター', 'hoge\hoge', $getConditions);

        $result = $this->repo->findById($jobId->code());
        $this->assertTrue(isset($result));
    }
}
