<?php

use App\Domain\Course\Course;
use App\Domain\GuildMember\RepositoryInterface\GuildMemberRepositoryInterface;
use App\Infrastracture\GuildMember\GuildMemberOnMemoryRepositoryImpl;
use App\Domain\GuildMember\GuildMember;
use App\Domain\GuildMember\Spec\GuildMemberSpec;
use App\Domain\GuildMember\Factory\GuildMemberFactory;
use App\Domain\GuildMember\ValueObjects\Gender;
use App\Domain\GuildMember\ValueObjects\MailAddress;
use App\Domain\GuildMember\ValueObjects\StudentNumber;
use Tests\Sampler;

/**
 * Created by PhpStorm.
 * User: user
 * Date: 2017/10/27
 * Time: 12:19
 */


class GuildMemberSpecTest extends \Tests\TestCase
{
    use Sampler;

    protected $repo;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = app(GuildMemberRepositoryInterface::class);

        $guildMember = $this->sampleGuildMember(['studentNumber' => 'B4000']);
        $this->repo->save($guildMember);
    }

    function testSuccess()
    {
        $studentNumber = new StudentNumber('B4000');
        $this->assertTrue(GuildMemberSpec::isExistStudentNumber($studentNumber));

        $this->assertTrue(GuildMemberSpec::isCompleteItem($this->repo->findByStudentNumber($studentNumber)));
    }


    function testFail()
    {
        $studentNumber = new StudentNumber('B1111');
        $this->assertFalse(GuildMemberSpec::isExistStudentNumber($studentNumber));

        $this->assertFalse(GuildMemberSpec::isCompleteItem(new GuildMember()));
    }
}
