<?php
/**
 * Created by PhpStorm.
 * User: yamagon
 * Date: 2017/11/10
 * Time: 11:30
 */

namespace Tests\Repository;


use App\Domain\Party\ValueObjects\ActivityEndDate;
use App\Domain\PartyWrittenRequest\RepositoryInterface\PartyWrittenRequestRepositoryInterface;
use App\Domain\ProductionIdea\ProductionIdea;
use App\Domain\WantedMember\ValueObjects\WantedRole;
use Tests\TestCase;

class PartyWrittenRequestTest extends TestCase
{
    protected $partyWrittenRequestRepository;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->partyWrittenRequestRepository = app(PartyWrittenRequestRepositoryInterface::class);
    }

    public function testSave()
    {
        $applicantId = "11";
        $activityEndDate = new ActivityEndDate('1431670515');
        $productionIdea = new ProductionIdea();
        $wantedRoleLis[] = new WantedRole();
    }

    public function testFindById()
    {
    }
}