<?php
/**
 * Created by PhpStorm.
 * User: yamagon
 * Date: 2017/10/27
 * Time: 11:31
 */

namespace Tests\Repository;


use App\Domain\ProductionType\Factory\ProductionTypeFactory;
use App\Domain\ProductionType\ProductionType;
use App\Domain\ProductionType\RepositoryInterface\ProductionTypeRepositoryInterface;
use Tests\TestCase;

class ProductionTypeRepositoryTest extends TestCase
{
    /* @var ProductionTypeRepositoryInterface $repo */
    protected $repo;
    protected $factory;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = app(ProductionTypeRepositoryInterface::class);
        $this->factory = new ProductionTypeFactory();
    }

    public function testSave()
    {
        $id = "aaa";
        $productionTypeName = "制作物の種類名";
        $productionType = $this->factory->createProductionType($productionTypeName, $id);
        $this->repo->save($productionType);
        $productionType2 = $this->repo->findById($id);
        $this->assertTrue($productionType2->productionTypeName() === $productionTypeName);
    }

    public function testFindById()
    {
        $productionType = $this->factory->createProductionType('種類名1','abc');
        $this->repo->save($productionType);
        $productionType2 = $this->factory->createProductionType('種類名2','def');
        $this->repo->save($productionType2);
        $findProductionType = $this->repo->findById('abc');
        $result = $findProductionType->id() === $productionType->id() && $findProductionType->productionTypeName() === $productionType->productionTypeName();
        $this->assertTrue($result);

        // 指定したIDがなかった場合にnullが帰るかどうか
        $this->assertTrue($this->repo->findById('80') === null);
    }
}