<?php
/**
 * Created by PhpStorm.
 * User: yamagon
 * Date: 2017/10/27
 * Time: 11:31
 */

namespace Tests\Repository;


use App\Domain\ProductionType\Factory\ProductionTypeFactory;
use App\Domain\ProductionType\ProductionType;
use App\Domain\ProductionType\RepositoryInterface\ProductionTypeRepositoryInterface;
use Tests\TestCase;

class ProductionTypeRepositoryTest extends TestCase
{
    /* @var ProductionTypeRepositoryInterface $repo */
    protected $repo;
    protected $factory;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = app(ProductionTypeRepositoryInterface::class);
        $this->factory = new ProductionTypeFactory();

        // オンメモリー時のみ初期値を用意する
        $productionType = $this->factory->createProductionType('種類名1');
        $this->repo->save($productionType);
        $productionType2 = $this->factory->createProductionType('種類名2');
        $this->repo->save($productionType2);
    }

    public function testFindByName()
    {
        $findProductionType = $this->repo->findByName('種類名1');
        $result = $findProductionType->name() === '種類名1';
        $this->assertTrue($result);

        // 指定したIDがなかった場合にnullが帰るかどうか
        $this->assertTrue($this->repo->findByName('ほげ') === null);
    }
}