<?php
/**
 * Created by PhpStorm.
 * User: yamagon
 * Date: 2017/10/27
 * Time: 11:31
 */

namespace Tests\Repository;


use App\Domain\ProductionType\ProductionType;
use App\Domain\ProductionType\RepositoryInterface\ProductionTypeRepositoryInterface;
use Tests\TestCase;

class ProductionTypeRepositoryTest extends TestCase
{
    /* @var ProductionTypeRepositoryInterface $repo */
    protected $repo;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = app(ProductionTypeRepositoryInterface::class);
    }

    public function testSave()
    {
        $productionType = new ProductionType('1','aaa');
        $this->repo->save($productionType);
        $this->assertTrue(true);
    }

    public function testFindById()
    {
        $productionType = new ProductionType('2','bbb');
        $this->repo->save($productionType);
        $productionType2 = new ProductionType('3','ccc');
        $this->repo->save($productionType2);
        $findProductionType = $this->repo->findById('2');
        $result = $findProductionType->Id() === $productionType->Id() && $findProductionType->ProductionTypeName() === $productionType->ProductionTypeName();
        $this->assertTrue($result);
    }
}