<?php
/**
 * Created by PhpStorm.
 * User: yamagon
 * Date: 2017/11/17
 * Time: 12:44
 */

namespace Tests\Controller\SignIn;

use App\ApplicationService\GuildMemberAppService;
use App\Domain\Course\RepositoryInterface\CourseRepositoryInterface;
use App\Domain\GuildMember\ValueObjects\Gender;
use App\Domain\GuildMember\ValueObjects\LoginInfo;
use App\Domain\GuildMember\ValueObjects\MailAddress;
use App\Domain\GuildMember\ValueObjects\PassWord;
use App\Domain\GuildMember\ValueObjects\StudentNumber;
use App\Infrastracture\AuthData\AuthData;
use Illuminate\Support\Facades\Auth;
use Tests\Sampler;
use Tests\TestCase;

class SignInStoreTest extends TestCase
{
    use Sampler;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $guildMember = $this->sampleGuildMember(['mailAddress' => 'B4000@oic.jp', 'password' => 'testPassword']);
        $authData = AuthData::findByLoginInfo(new LoginInfo($guildMember->mailAddress(), new PassWord("testPassword")));
    }

    public function testSuccess()
    {
        $response = $this->post(route('post_sign_in'),[
            'mail_address' => 'B4000@oic.jp',
            'password' => 'testPassword',
        ]);

        $response->assertStatus(200);
    }

    public function testFail()
    {
        $response = $this->post(route('post_sign_in'),[
            'mail_address' => 'B9999@oic.jp',
            'password' => 'testPassword',
        ]);

        $response->assertStatus(401);
    }
}