<?php

use App\Presentation\PartyParticipationRequestFacade;
use Tests\Sampler;
use Tests\TestCase;

/**
 * Created by PhpStorm.
 * User: yamagon
 * Date: 2017/12/27
 * Time: 22:01
 */

/**
 * 自分が申請しているパーティ参加申請のリストを取得するテスト
 */
class FindStudentNumberPartyParticipationRequestListTest extends TestCase
{
    use Sampler;

    /* @var PartyParticipationRequestFacade $partyParticipationRequestFacade */
    protected $partyParticipationRequestFacade;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->partyParticipationRequestFacade = app(PartyParticipationRequestFacade::class);

        $this->partyParticipationRequestFacade->registerPartyParticipationRequest("abcd1","w1", "B4999");
        $this->partyParticipationRequestFacade->registerPartyParticipationRequest("abcd2","w2", "B4999");
        $this->partyParticipationRequestFacade->registerPartyParticipationRequest("abcd3","w3", "B4999");
        $this->partyParticipationRequestFacade->registerPartyParticipationRequest("abcd4","w4", "B4000");
        $this->partyParticipationRequestFacade->registerPartyParticipationRequest("abcd1","w5", "B4999");
    }

    public function testSuccess()
    {
        $findStudentNumberPartyParticipationRequestList = $this->partyParticipationRequestFacade->findStudentNumberPartyParticipationRequestList("B4999");

        $this->assertTrue($findStudentNumberPartyParticipationRequestList[0]->wantedRoleId() == "w1");
        $this->assertTrue($findStudentNumberPartyParticipationRequestList[1]->wantedRoleId() == "w2");
        $this->assertTrue($findStudentNumberPartyParticipationRequestList[2]->wantedRoleId() == "w3");
        $this->assertTrue($findStudentNumberPartyParticipationRequestList[3]->wantedRoleId() == "w5");

        // 見つからなかった場合空の配列を返す
        $this->assertTrue($this->partyParticipationRequestFacade->findStudentNumberPartyParticipationRequestList("B4444") === []);
    }

}