<?php

use App\Domain\PartyParticipationRequest\RepositoryInterface\PartyParticipationRequestRepositoryInterface;
use App\Presentation\PartyParticipationRequestFacade;
use Tests\Sampler;

/**
 * Created by PhpStorm.
 * User: yamagon
 * Date: 2018/01/05
 * Time: 17:57
 */

class ReplyPartyParticipationRequestTest extends \Tests\TestCase
{
    use Sampler;

    /* @var PartyParticipationRequestFacade $partyParticipationRequestFacade*/
    protected $partyParticipationRequestFacade;
    /* @var PartyParticipationRequestRepositoryInterface $partyParticipationRequestRepository */
    protected $partyParticipationRequestRepository;

    protected $party;
    protected $guildMember;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->partyParticipationRequestFacade = app(PartyParticipationRequestFacade::class);
        $this->partyParticipationRequestRepository = app(PartyParticipationRequestRepositoryInterface::class);
        $this->party = $this->sampleParty();
    }

    public function testSuccess()
    {
        $this->partyParticipationRequestFacade->sendPartyParticipationRequest($this->party->id(),"abcd", "B4999");

        $replyPartyParticipationRequestId = $this->partyParticipationRequestFacade->replyPartyParticipationRequest($this->party->id(), $this->party->partyManagerId()->code(),"B4999","permit");
        $partyParticipationRequest = $this->partyParticipationRequestRepository->findById($replyPartyParticipationRequestId);

        $this->assertTrue($partyParticipationRequest->partyId() === $this->party->id());
        $this->assertTrue($partyParticipationRequest->wantedRoleId() === "abcd");
        $this->assertTrue($partyParticipationRequest->guildMemberId()->code() === "B4999");
    }

    /**
     * パーティ参加申請へ返信したのがPartyの管理者じゃなかった場合
     *
     * @expectedException Exception
     */
    public function testManagerIdFail()
    {
        $this->partyParticipationRequestFacade->sendPartyParticipationRequest($this->party->id(),"abcd", "B4999");

        $replyPartyParticipationRequestId = $this->partyParticipationRequestFacade->replyPartyParticipationRequest($this->party->id(), "B5000","B4999","permit");
    }
}