<?php

use App\ApplicationService\EventAppService;
use App\Domain\Event\EventRepositoryInterface;
use App\Domain\Event\ValueObjects\EvaluationPeriod;
use App\Domain\Event\ValueObjects\EventHoldPeriod;
use App\Domain\Event\ValueObjects\ReleasePeriod;
use Tests\TestCase;

/**
 * Created by PhpStorm.
 * User: user
 * Date: 2018/02/04
 * Time: 11:07
 */


class EventAppServiceTest extends TestCase
{
    /* @var EventRepositoryInterface $repo */
    protected $repo;
    /* @var EventAppService $appService */
    protected $appService;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = app(EventRepositoryInterface::class);
        $this->appService = app(EventAppService::class);
    }

    public function testSuccess()
    {
        $id = $this->appService->issueEvent(
            'MF',
            'oic',
            '作品展',
            new ReleasePeriod('2020-01-01', '2020-02-01'),
            new EventHoldPeriod('2020-01-02', '2020-01-15'),
            new EvaluationPeriod('2020-01-16', '2020-01-30')
        );
        $result = $this->repo->findById($id->code());
        $this->assertTrue(isset($result));
    }
}
