<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 2017/10/24
 * Time: 11:33
 */

namespace Tests\Domain\Course;

use App\Domain\Course\Course;
use App\Domain\Course\RepositoryInterface\CourseRepositoryInterface;
use App\Infrastracture\Course\CourseOnMemoryRepositoryImpl;
use App\Domain\Course\Spec\CourseSpec;
use Tests\TestCase;

class CourseSpecTest extends TestCase
{
    protected $repo;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = app(CourseRepositoryInterface::class);
        $course = new Course('1','a');
        $this->repo->save($course);
    }

    function testSuccess()
    {
        $code = '1';
        $this->assertTrue(CourseSpec::isExistCode($code));
    }


    function testFail()
    {
        $code = '9999';
        $this->assertFalse(CourseSpec::isExistCode($code));
    }
}
