<?php
/**
 * Created by PhpStorm.
 * User: yamagon
 * Date: 2017/10/27
 * Time: 11:12
 */

namespace Tests\Domain\ProductionType;


use App\Domain\ProductionType\ProductionType;
use App\Domain\ProductionType\RepositoryInterface\ProductionTypeRepositoryInterface;
use App\Domain\ProductionType\Spec\ProductionTypeSpec;
use Tests\Sampler;
use Tests\TestCase;

class ProductionTypeSpecTest extends TestCase
{
    use Sampler;
    protected $repo;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    function testSuccess()
    {
        $name = $this->sampleProductionType()->name();
        $this->assertTrue(ProductionTypeSpec::isExistCode($name));
    }


    function testFail()
    {
        $name = '2';
        $this->assertFalse(ProductionTypeSpec::isExistCode($name));
    }
}