<?php
/**
 * Created by PhpStorm.
 * User: yamagon
 * Date: 2017/10/27
 * Time: 11:12
 */

namespace Tests\Domain\ProductionType;


use App\Domain\ProductionType\ProductionType;
use App\Domain\ProductionType\RepositoryInterface\ProductionTypeRepositoryInterface;
use App\Domain\ProductionType\Spec\ProductionTypeSpec;
use Tests\TestCase;

class ProductionTypeSpecTest extends TestCase
{
    protected $repo;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = app(ProductionTypeRepositoryInterface::class);
        $productionType = new ProductionType('1','a');
        $this->repo->save($productionType);
    }

    function testSuccess()
    {
        $code = '1';
        $this->assertTrue(ProductionTypeSpec::isExistCode($code));
    }


    function testFail()
    {
        $code = '2';
        $this->assertFalse(ProductionTypeSpec::isExistCode($code));
    }
}