<?php

namespace Tests\Presentation\Job;

use App\Domain\GetCondition\GetCondition;
use App\Domain\Job\JobRepositoryInterface;
use App\Presentation\Job\JobServiceFacade;
use Tests\TestCase;

/**
 * Created by PhpStorm.
 * User: user
 * Date: 2017/12/12
 * Time: 16:47
 */


class JobServiceFacadeTest extends TestCase
{
    /* @var JobRepositoryInterface $repo */
    protected $repo;
    /* @var JobServiceFacade $facade */
    private $facade;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = app(JobRepositoryInterface::class);
        $this->facade = app(JobServiceFacade::class);
    }

    public function testSuccess()
    {
        $getCondition1 = new GetCondition('aaaa', 10);
        $getCondition2 = new GetCondition('bbbb', 15);

        $getConditions[] = $getCondition1;
        $getConditions[] = $getCondition2;

        $code = $this->facade->registerJob('javaマスター', 'hoge\hogehoge', $getConditions);

        $result = $this->repo->findById($code);
        $this->assertTrue(isset($result));
    }
}
