<?php

use App\Domain\Event\EventRepositoryInterface;
use App\Presentation\EventFacade;
use Tests\TestCase;

/**
 * Created by PhpStorm.
 * User: user
 * Date: 2018/02/04
 * Time: 11:23
 */


class EventFacadeTest extends TestCase
{
    /* @var EventRepositoryInterface $repo */
    protected $repo;
    /* @var EventFacade $facade */
    protected $facade;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = app(EventRepositoryInterface::class);
        $this->facade = app(EventFacade::class);
    }

    public function testSuccess()
    {
        $id = $this->facade->issueEvent(
            'MF',
            'oic',
            '作品展',
            '2020-01-01',
            '2020-02-01',
            '2020-01-02',
            '2020-01-15',
            '2020-01-16',
            '2020-01-30'
        );
        $result = $this->repo->findById($id);
        $this->assertTrue(isset($result));
    }
}
