<?php


use App\ApplicationService\GuildMemberAppService;
use App\Domain\Course\RepositoryInterface\CourseRepositoryInterface;
use App\Domain\GuildMember\ValueObjects\LoginInfo;
use App\Domain\GuildMember\ValueObjects\MailAddress;
use App\Domain\GuildMember\ValueObjects\PassWord;
use App\Infrastracture\AuthData\AuthData;
use Illuminate\Support\Facades\Auth;

class GuildMemberDeleteTest extends \Tests\TestCase
{
    use \Tests\Sampler;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $guildMember = $this->sampleGuildMember(['password' => new PassWord('abcd1234')]);
        $authData = AuthData::findByLoginInfo(new LoginInfo($guildMember->mailAddress(), new PassWord("abcd1234")));
        $this->actingAs($authData);
    }

    public function testSuccess()
    {
        $response = $this->delete(route('destroy_guild_member'));

        $response->assertStatus(200);
    }

    public function testFail()
    {
        Auth::logout();
        $response = $this->delete(route('destroy_guild_member'));

        $response->assertStatus(302);
    }
}