<?php


use App\ApplicationService\GuildMemberAppService;
use App\Domain\Course\RepositoryInterface\CourseRepositoryInterface;
use App\Domain\GuildMember\ValueObjects\StudentNumber;
use App\Domain\GuildMember\ValueObjects\Gender;
use App\Domain\GuildMember\ValueObjects\MailAddress;
use App\Domain\GuildMember\ValueObjects\LoginInfo;
use App\Domain\GuildMember\ValueObjects\PassWord;

class GuildMemberDeleteTest extends \Tests\TestCase
{
    /* @var GuildMemberAppService $guildMemberAppService*/
    protected $guildMemberAppService;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->guildMemberAppService = app(GuildMemberAppService::class);
        /* @var CourseRepositoryInterface $courseRepository */
        $courseRepository = app(CourseRepositoryInterface::class);
        $authData = $this->guildMemberAppService->registerMember(
            new StudentNumber('B4000'),
            'テスト太郎',
            $courseRepository->all()[0],
            new Gender(Gender::MALE),
            new MailAddress('b4000@oic.jp'),
            new LoginInfo(new MailAddress('b4000@oic.jp'), new PassWord('12345678'))
        );
        $this->actingAs($authData);
    }

    public function testSuccess()
    {
        $response = $this->delete(route('destroy_guild_member'),[
            'name' => 'テスト太郎',
            'course_id' => '1',
            'gender' => 'male',
        ]);

        $response->assertStatus(200);
    }
}