<?php
/**
 * Created by PhpStorm.
 * User: yamagon
 * Date: 2017/11/17
 * Time: 12:44
 */

namespace Tests\Controller\SignUp;

use Tests\TestCase;

class SignUpStoreTest extends TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testSuccess()
    {
        $response = $this->post(route('post_sign_up'),[
            'student_number' => 'B4000',
            'name' => 'テスト太郎',
            'course_id' => '1',
            'gender' => 'male',
            'mail_address' => 'B4000@oic.jp',
            'password' => 'testPassword',
        ]);

        $response->assertStatus(200);
    }
}